# docker run -p 15672:15672 -p 5672:5672 rabbitmq:3-management
name: clever
plugins: ["logger", "validator", "router", "http", "amqp", "prometheus"]
maintenanceMode: false

http:
  server:
    handler: hapi
    port: 3000
  router:
    enabled: true
  # extensions:
  #   - preRequest
  #   - preResponse
  #   - postRequest
  #   - postResponse

logger:
  defaultLogger: true
  # prettifyDefaultLogger: false
  # streams:
  #   pretty:
  #     level: debug
  #     translateTime: true

router:
  routes:
    directory: src/actions
    prefix: debug
    enabledGenericActions:
      - health

amqp:
  transport:
    connection:
      # host:
      #   - host: localhost
      #     port: 5672
      # login: guest
      # password: guest
      host:
        - host: amqp.staging.svc.cluster.local
          port: 5672
      login: guest
      password: gWTfbOcGIudKXm4IXstUEBnL
      vhost: /
  router:
    enabled: true

tests:
  hosts:
    debug: test.staging.streamlayer.io
    dashboard: admin.staging.streamlayer.io
    web: grpc-web.staging.streamlayer.io
    proxy: grpc.staging.streamlayer.io
    chat: chat.staging.streamlayer.io
  securePort: 443
  users:
    - id: v@makeomatic.ru
      password: verylongdemopassword
    - id: renat0014@gmail.com
      password: verylongdemopassword
